Repository systemd/mkosi, pull requests merged in 2022-07, with the labels that each got.

#1047 Drop bundle package type
  mkosi/backend.py
Labels: quick-review

#1065 Fix exception when removing partition after it has been written
  mkosi/__init__.py
Labels: reviewed/needs-rework

#1071 Always define args.architecture and add args.host_architecture
  mkosi/__init__.py
  mkosi/backend.py
  tests/test_config_parser.py
Labels: good-to-merge/waiting-for-ci

#1074 Force initializing the partition table every time create_image is called
  .github/workflows/ci.yml
  mkosi/__init__.py
  mkosi/gentoo.py
Labels: good-to-merge/waiting-for-ci

#1052 Pass kernel args to systemd when booting in nspawn
  mkosi/__init__.py
Labels: good-to-merge/waiting-for-ci

#1036 Centos + variants improvements
  mkosi/__init__.py
  mkosi/backend.py
Labels: good-to-merge/waiting-for-ci

#1053 Only pass arguments to build script when verb is "build"
  mkosi/__init__.py
Labels: good-to-merge/waiting-for-ci

#1060 Move debian/ubuntu kernel-install workaround to a kernel-install script
  mkosi/__init__.py
  mkosi/resources/dpkg-reconfigure-dracut.install
Labels: good-to-merge/waiting-for-ci
