Repository systemd/mkosi, pull requests merged in 2022-06, with the labels that each got.

#994 mkosi: create bmap before compression
  mkosi/__init__.py
Labels: good-to-merge/waiting-for-ci

#958 Tweaks to argparse setup to make --help output nicer
  man/mkosi.1
  mkosi.md
  mkosi/__init__.py
  mkosi/backend.py
Labels: reviewed/needs-rework

#1010 Drop choices param from --debug option spec
  mkosi/__init__.py
Labels: good-to-merge/waiting-for-ci

#1015 Add veritysetup.target to initrd
  mkosi/__init__.py
Labels: good-to-merge/waiting-for-ci

#1007 Rework initramfs generation (again)
  mkosi/__init__.py
Labels: please-review

#974 ci: Update to Ubuntu 22.04 LTS
  .github/workflows/ci.yml
  action.yaml
  action/mkosi.default
  action/setup-github-actions.sh
  action/setup-pacman.sh
  mkosi/__init__.py
  tests/test_config_parser.py
Labels: good-to-merge/waiting-for-ci

#1017 debian/ubuntu: Handle scenario where systemd-boot is a split package
  mkosi/__init__.py
  mkosi/backend.py
  mkosi/manifest.py
Labels: good-to-merge/waiting-for-ci

#1016 Drop sfdisk grain support check
  mkosi/backend.py
Labels: good-to-merge/waiting-for-ci

#1019 action: Build only systemd-nspawn
  action.yaml
Labels: good-to-merge/waiting-for-ci

#1004 Handle rpmdb move
  mkosi/__init__.py
  mkosi/manifest.py
Labels: good-to-merge/waiting-for-ci
