Repository systemd/mkosi, pull requests merged in 2023-06, with the labels that each got.

#1604 ci: add --debug flag
  .github/workflows/ci.yml
Labels: good-to-merge/waiting-for-ci

#1618 Seed package manager config
  NEWS.md
  mkosi.md
  mkosi/__init__.py
  mkosi/config.py
  mkosi/distributions/arch.py
  mkosi/distributions/debian.py
  mkosi/distributions/fedora.py
  mkosi/state.py
  tests/test_parse_load_args.py
  tests/test_util.py
Labels: good-to-merge/waiting-for-ci

#1628 qemu: Use SOCK_STREAM for notify socket
  mkosi/qemu.py
Labels: good-to-merge/waiting-for-ci

#1636 Generate argument parser from config setting list
  mkosi/config.py
  mkosi/distributions/debian.py
  mkosi/run.py
Labels: good-to-merge/waiting-for-ci

#1632 Support Ukify config
  mkosi.md
  mkosi/__init__.py
Labels: reviewed/needs-rework

#1642 fedora: fix RemovePackages with dnf5
  mkosi/distributions/fedora.py
Labels: ci-fails/needs-rework
