Repository systemd/mkosi, pull requests merged in 2023-11, with the labels that each got.

#2043 Fix broken KernelModuleIncludes implementation
  mkosi/config.py
Labels: needs-rebase

#2061 mkosi: add "burn" verb 🔥🔥🔥
  mkosi/__init__.py
  mkosi/burn.py
  mkosi/config.py
  mkosi/resources/mkosi.md
Labels: good-to-merge/waiting-for-ci, new-feature

#2069 Release 19
  mkosi/config.py
  pyproject.toml
Labels: dont-merge

#2074 Rename Compression.zst to Compression.zstd
  mkosi/__init__.py
  mkosi/config.py
  mkosi/resources/mkosi.md
  tests/test_config.py
Labels: good-to-merge/waiting-for-ci

#2073 Ttyama0
  mkosi/__init__.py
  mkosi/burn.py
  mkosi/config.py
  mkosi/mounts.py
Labels: good-to-merge/with-minor-suggestions

#2093 Add ability to create passwordless root account
  mkosi/__init__.py
  mkosi/resources/mkosi.md
Labels: good-to-merge/waiting-for-ci, squash-on-merge

#2095 autologin: use a helper method to reduce boilerplate
  mkosi/__init__.py
Labels: good-to-merge/with-minor-suggestions

#2106 Set atime and mtime of scripts to zero
  mkosi/__init__.py
Labels: good-to-merge/waiting-for-ci

#2111 Revert "ci: enable jammy-proposed-updates to get new libsolv"
  .github/workflows/ci.yml
Labels: ci
