Repository systemd/mkosi, pull requests merged in 2023-04, with the labels that each got.

#1428 Simplify autologin
  mkosi.md
  mkosi/__init__.py
  mkosi/backend.py
  mkosi/distributions/arch.py
  mkosi/distributions/debian.py
  mkosi/distributions/mageia.py
  mkosi/distributions/opensuse.py
  mkosi/resources/console_getty_autologin.conf
  mkosi/resources/getty_autologin.conf
  mkosi/resources/serial_getty_autologin.conf
Labels: good-to-merge/waiting-for-ci

#1444 Use pager for summary and help
  man/mkosi.1
  mkosi.md
  mkosi/__init__.py
  mkosi/backend.py
  mkosi/config.py
  mkosi/pager.py
Labels: good-to-merge/waiting-for-ci

#1287 Document various ways to boot with qemu directly and how to override kernel command lines
  man/mkosi.1
  mkosi.md
Labels: needs-review

#1459 Don't make output an absolute path while parsing
  mkosi/__init__.py
  mkosi/config.py
Labels: good-to-merge/waiting-for-ci

#1467 Redirect run() input from /dev/null, adjust formatting
  mkosi/__init__.py
  mkosi/manifest.py
  mkosi/run.py
Labels: good-to-merge/waiting-for-ci

#1468 Split up --base-image into --base-tree and --overlay
  NEWS.md
  action.yaml
  mkosi.md
  mkosi/__init__.py
  mkosi/backend.py
  mkosi/config.py
  mkosi/manifest.py
  mkosi/mounts.py
Labels: good-to-merge/waiting-for-ci

#1472 Path expansion
  mkosi/__init__.py
  mkosi/backend.py
  mkosi/config.py
  mkosi/run.py
Labels: good-to-merge/waiting-for-ci

#1488 Allow setting empty environment variables
  mkosi/__init__.py
Labels: good-to-merge/waiting-for-ci

#1496 Support matching against any of a list of releases
  mkosi.md
  mkosi/config.py
Labels: good-to-merge/waiting-for-ci

#1490 Enable --repo-dir for Debian and Ubuntu
  mkosi.md
  mkosi/config.py
  mkosi/distributions/debian.py
  mkosi/install.py
  mkosi/util.py
Labels: needs-rebase

#1504 Add matching on image ID and version
  .github/workflows/ci.yml
  action.yaml
  mkosi.md
  mkosi/config.py
  tests/test_parse_load_args.py
Labels: ci-fails/needs-rework

#1508 Allow globs if image ID matches and implement not equal for image version matches
  .github/workflows/ci.yml
  mkosi.md
  mkosi/config.py
  tests/test_parse_load_args.py
Labels: good-to-merge/waiting-for-ci
