Repository systemd/mkosi, pull requests merged in 2023-08, with the labels that each got.

#1724 Make sure outputs are always prefixed with the output name
  mkosi/__init__.py
Labels: good-to-merge/waiting-for-ci

#1725 Give scripts access to sys.stdin
  mkosi/__init__.py
  mkosi/distributions/centos.py
  mkosi/run.py
Labels: good-to-merge/waiting-for-ci

#1728 Make sure package managers are always configured
  mkosi/__init__.py
  mkosi/distributions/__init__.py
  mkosi/distributions/arch.py
  mkosi/distributions/centos.py
  mkosi/distributions/debian.py
  mkosi/distributions/fedora.py
  mkosi/distributions/gentoo.py
  mkosi/distributions/mageia.py
  mkosi/distributions/openmandriva.py
  mkosi/distributions/opensuse.py
Labels: good-to-merge/waiting-for-ci

#1731 opensuse: Install distribution-release by default
  mkosi.md
  mkosi/__init__.py
  mkosi/distributions/opensuse.py
Labels: good-to-merge/waiting-for-ci

#1734 Make sure we mount cache and workspace writable when running package managers
  mkosi/distributions/gentoo.py
  mkosi/installer/apt.py
  mkosi/installer/dnf.py
  mkosi/installer/pacman.py
  mkosi/installer/zypper.py
Labels: good-to-merge/waiting-for-ci

#1740 Get rid of check_root() function
  mkosi/__init__.py
  mkosi/config.py
  mkosi/util.py
Labels: good-to-merge/waiting-for-ci

#1742 CI fixes
  .github/mkosi.conf.d/20-alma.conf
  .github/mkosi.conf.d/20-centos.conf
  .github/mkosi.conf.d/20-rocky.conf
  .github/workflows/ci.yml
Labels: good-to-merge/waiting-for-ci

#1744 Stuff
  mkosi.md
  mkosi/config.py
Labels: good-to-merge/waiting-for-ci

#1750 Add logging to qemu_check_kvm_support()
  mkosi/__init__.py
  mkosi/config.py
  mkosi/qemu.py
  mkosi/util.py
Labels: good-to-merge/waiting-for-ci

#1752 Move network argument from chroot_cmd() to bwrap()
  mkosi/__init__.py
  mkosi/distributions/gentoo.py
  mkosi/installer/apt.py
  mkosi/installer/dnf.py
  mkosi/installer/pacman.py
  mkosi/installer/zypper.py
  mkosi/run.py
Labels: good-to-merge/waiting-for-ci

#1689 gentoo: swith to llvm (clang)
  mkosi/distributions/gentoo.py
Labels: ci-fails/needs-rework

#1778 List all subpackages in pyproject.toml
  mkosi/config.py
  pyproject.toml
Labels: good-to-merge/waiting-for-ci

#1779 Make sure the private tmpfs in bwrap() doesn't hide workspace
  mkosi/run.py
Labels: good-to-merge/waiting-for-ci

#1780 Don't use capsh to figure out capabilities
  mkosi/run.py
Labels: good-to-merge/waiting-for-ci

#1784 Make sure we use python-pefile from the tools tree
  mkosi/__init__.py
Labels: good-to-merge/waiting-for-ci

#1786 set Dir::Etc option on apt based distros
  mkosi/installer/apt.py
Labels: good-to-merge/waiting-for-ci

#1816 mkosi: adjust messages about missing cert+key
  mkosi/config.py
Labels: good-to-merge/waiting-for-ci

#1822 Archive fixes
  mkosi/__init__.py
  mkosi/config.py
  mkosi/distributions/gentoo.py
  mkosi/installer/apt.py
  mkosi/installer/dnf.py
  mkosi/installer/pacman.py
  mkosi/installer/zypper.py
  mkosi/run.py
Labels: good-to-merge/with-minor-suggestions

#1837 add config setting seed to set systemd-repart `--seed`
  mkosi/__init__.py
  mkosi/config.py
  mkosi/resources/mkosi.md
Labels: good-to-merge/waiting-for-ci

#1844 Disable index and metacopy options of overlayfs
  mkosi/mounts.py
Labels: good-to-merge/waiting-for-ci
