Repository systemd/mkosi, pull requests merged in 2023-09, with the labels that each got.

#1859 CI: pin CentOS 9 kernel to workaround panic on shutdown
  .github/mkosi.conf.d/20-alma-rocky.conf
  .github/mkosi.conf.d/20-centos9.conf
Labels: ci, quick-review

#1867 Do not run modinfo on builtin modules
  mkosi/kmod.py
Labels: good-to-merge/waiting-for-ci

#1870 Follow up for 5462f5e31c4223a001c2ed5aa8d44177fb8454fc
  mkosi/config.py
Labels: good-to-merge/waiting-for-ci

#1872 ci: use https for OpenSUSE again
  .github/mkosi.conf.d/20-opensuse.conf
Labels: ci

#1884 mkosi: be clearer what "uki" output format means
  mkosi/resources/mkosi.md
Labels: documentation

#1896 Add ruff config to `pyprojects.toml` and address its warnings
  mkosi/__init__.py
  mkosi/config.py
  mkosi/distributions/__init__.py
  mkosi/distributions/centos.py
  mkosi/distributions/fedora.py
  mkosi/distributions/opensuse.py
  mkosi/installer/apt.py
  mkosi/log.py
  mkosi/mounts.py
  mkosi/partition.py
  mkosi/qemu.py
  mkosi/run.py
  mkosi/util.py
  pyproject.toml
  tests/test_config.py
  tests/test_versioncomp.py
Labels: good-to-merge/waiting-for-ci

#1919 Set MKOSI_UID and MKOSI_GID when running scripts
  NEWS.md
  mkosi/__init__.py
  mkosi/mounts.py
  mkosi/resources/mkosi.md
  mkosi/run.py
  mkosi/state.py
Labels: good-to-merge/waiting-for-ci

#1923 Mount over /etc/passwd when building an image and running build script
  mkosi/__init__.py
  mkosi/mounts.py
  mkosi/run.py
  mkosi/state.py
Labels: good-to-merge/waiting-for-ci

#1926 Pass command line arguments to build script again
  .github/mkosi.conf.d/20-centos.conf
  .github/mkosi.conf.d/20-centos9.conf
  mkosi/__init__.py
  mkosi/config.py
  mkosi/distributions/arch.py
  mkosi/distributions/centos.py
  mkosi/distributions/debian.py
  mkosi/distributions/fedora.py
  mkosi/distributions/opensuse.py
  mkosi/resources/mkosi.md
Labels: good-to-merge/waiting-for-ci
