Repository systemd/mkosi, pull requests merged in 2024-09, with the labels that each got.

#3005 Various mypy fixes
  mkosi/__init__.py
  mkosi/backport.py
  mkosi/bootloader.py
  mkosi/config.py
  mkosi/distributions/arch.py
  mkosi/distributions/azure.py
  mkosi/distributions/centos.py
  mkosi/distributions/debian.py
  mkosi/distributions/fedora.py
  mkosi/distributions/kali.py
  mkosi/distributions/mageia.py
  mkosi/distributions/openmandriva.py
  mkosi/distributions/opensuse.py
  mkosi/distributions/rhel.py
  mkosi/distributions/rhel_ubi.py
  mkosi/distributions/ubuntu.py
  mkosi/installer/apt.py
  mkosi/installer/dnf.py
  mkosi/installer/pacman.py
  mkosi/installer/zypper.py
  mkosi/kmod.py
  mkosi/log.py
  mkosi/manifest.py
  mkosi/partition.py
  mkosi/run.py
  mkosi/sandbox.py
  mkosi/user.py
  mkosi/util.py
  mkosi/versioncomp.py
  pyproject.toml
  tests/test_json.py
Labels: good-to-merge/with-minor-suggestions

#3053 Add `OutputMode=` option
  mkosi/__init__.py
  mkosi/config.py
  mkosi/initrd.py
  mkosi/resources/man/mkosi.md
  tests/test_json.py
Labels: good-to-merge/waiting-for-ci

#3056 Use run0 instead of refusing to run commands that need root unprivileged
  mkosi/__init__.py
  mkosi/burn.py
  mkosi/config.py
  mkosi/sysupdate.py
Labels: needs-news-entry

#3060 Add Incremental=strict
  mkosi/__init__.py
  mkosi/config.py
  mkosi/documentation.py
  mkosi/resources/man/mkosi.md
  tests/test_json.py
Labels: good-to-merge/waiting-for-ci

#3066 Don't explicitly bind mount in keyrings from host into sandbox
  mkosi/mounts.py
  mkosi/resources/man/mkosi.md
Labels: needs-news-entry

#3079 Fix wrongly-quoted string
  mkosi/__init__.py
Labels: good-to-merge/waiting-for-ci
