Repository systemd/mkosi, pull requests merged in 2024-11, with the labels that each got.

#3160 Fix qemu gui output on aarch64
  mkosi/qemu.py
Labels: good-to-merge/waiting-for-ci

#3164 Add sandbox verb
  mkosi.conf.d/40-tools/mkosi.conf
  mkosi.conf.d/40-tools/mkosi.conf.d/arch.conf
  mkosi.conf.d/40-tools/mkosi.conf.d/other.conf
  mkosi/__init__.py
  mkosi/config.py
  mkosi/mounts.py
  mkosi/qemu.py
  mkosi/resources/man/mkosi.1.md
  mkosi/resources/man/mkosi.news.7.md
  mkosi/resources/mkosi-tools/mkosi.conf
  mkosi/resources/mkosi-tools/mkosi.conf.d/10-arch.conf
  mkosi/resources/mkosi-tools/mkosi.conf.d/10-centos/mkosi.conf.d/20-epel-packages.conf
  mkosi/resources/mkosi-tools/mkosi.conf.d/10-debian-kali-ubuntu/mkosi.conf
  mkosi/resources/mkosi-tools/mkosi.conf.d/10-fedora/mkosi.conf
  mkosi/resources/mkosi-tools/mkosi.conf.d/10-opensuse.conf
  mkosi/run.py
Labels: good-to-merge/waiting-for-ci, needs-news-entry

#3201 Rename some opts to be more consistent
  mkosi/__init__.py
  mkosi/config.py
  mkosi/initrd.py
  mkosi/resources/man/mkosi.1.md
  tests/__init__.py
  tests/test_initrd.py
Labels: needs-rebase

#3210 kmod: do not append glob to search for firmware if it is already there
  mkosi/kmod.py
Labels: good-to-merge/waiting-for-ci

#3213 ci: make the output of the formatting job actionable
  .github/workflows/ci.yml
Labels: good-to-merge/waiting-for-ci

#3240 Don't resolve deps if we're reusing previous config
  mkosi/__init__.py
  mkosi/config.py
Labels: good-to-merge/with-minor-suggestions

#3241 Only remove initrd cache entries
  mkosi/__init__.py
Labels: good-to-merge/with-minor-suggestions

#3243 Fix Partition split_path calculation
  action.yaml
  mkosi/__init__.py
  mkosi/partition.py
Labels: good-to-merge/waiting-for-ci
