Repository systemd/mkosi, pull requests merged in 2024-06, with the labels that each got.

#2733 Add `UnifiedKernelImageFormat=` (attempt 2)
  mkosi/__init__.py
  mkosi/config.py
  mkosi/resources/mkosi.md
  tests/test_config.py
  tests/test_json.py
Labels: good-to-merge/waiting-for-ci

#2450 Two opensuse improvements
  mkosi/config.py
  mkosi/installer/dnf.py
  mkosi/installer/zypper.py
Labels: dont-merge, blocked, needs-news-entry

#2750 Update NEWS
  NEWS.md
Labels: good-to-merge/with-minor-suggestions

#2768 Fix missing mount in `mkosi.clean`
  mkosi/__init__.py
Labels: good-to-merge/waiting-for-ci

#2773 Set stdout/stderr of not found process to empty string instead of None
  mkosi/run.py
Labels: good-to-merge/waiting-for-ci

#2771 Add `mkosi.postoutput` scripts
  mkosi/__init__.py
  mkosi/config.py
  mkosi/resources/mkosi.md
  tests/test_json.py
Labels: good-to-merge/waiting-for-ci

#2775 Add dpkg and dpkg-query scripts
  mkosi/installer/apt.py
  mkosi/resources/mkosi.md
Labels: good-to-merge/waiting-for-ci

#2791 qemu/vmspawn: check for an uncompressed kernel too
  mkosi/__init__.py
Labels: good-to-merge/with-minor-suggestions

#2800 Don't rename vmlinux to vmlinuz when copying from /boot to /usr
  mkosi/__init__.py
Labels: good-to-merge/waiting-for-ci

#2797 SHA256SUMS fixes
  mkosi/__init__.py
Labels: good-to-merge/waiting-for-ci

#2804 Only use fw_cfg if credential name is not too long
  mkosi/qemu.py
Labels: good-to-merge/waiting-for-ci

#2806 Deal with systemd split packages added in Debian testing
  mkosi/resources/mkosi-initrd/mkosi.conf.d/10-debian-ubuntu/mkosi.conf
  mkosi/resources/mkosi-tools/mkosi.conf.d/10-debian-ubuntu.conf
Labels: good-to-merge/waiting-for-ci

#2805 [RFC] mkosi-initrd: provide a separate mkosi-initrd script
  .gitignore
  kernel-install/50-mkosi.install
  mkosi/initrd/__main__.py
  mkosi/initrd/resources/mkosi-initrd.md
  pyproject.toml
  tools/make-man-page.sh
Labels: good-to-merge/waiting-for-ci

#2809 Default to no secure boot for non-x86 architectures
  mkosi/qemu.py
Labels: good-to-merge/waiting-for-ci
