Repository systemd/mkosi, pull requests merged in 2024-03, with the labels that each got.

#2451 Add string strip prefix helper
  mkosi/config.py
  mkosi/distributions/fedora.py
  mkosi/sandbox.py
  mkosi/util.py
Labels: good-to-merge/waiting-for-ci

#2502 ci: Remove btrfs logic
  .github/workflows/ci.yml
Labels: dont-merge

#2508 Misc fixes for running mkosi as root on a shared build machines
  mkosi/__init__.py
  mkosi/config.py
Labels: good-to-merge/waiting-for-ci

#2516 Virtiofsd fixes
  mkosi/__init__.py
  mkosi/config.py
  mkosi/qemu.py
Labels: needs-news-entry

#2541 Set $HOME to the user's home directory in sync scripts
  mkosi/__init__.py
Labels: good-to-merge/waiting-for-ci

#2553 Capitalise inner JSON keys
  mkosi/config.py
  tests/test_json.py
Labels: good-to-merge/waiting-for-ci

#2561 Add CleanScripts=
  mkosi/__init__.py
  mkosi/config.py
  mkosi/resources/mkosi.md
  tests/test_json.py
Labels: good-to-merge/waiting-for-ci
