Repository systemd/mkosi, pull requests merged in 2025-02, with the labels that each got.

#3494 Add SplitArtifacts=roothash
  mkosi/__init__.py
  mkosi/config.py
  mkosi/partition.py
  mkosi/resources/man/mkosi.1.md
  mkosi/resources/mkosi-obs/mkosi.conf
  mkosi/resources/mkosi-obs/mkosi.postoutput
Labels: good-to-merge/waiting-for-ci

#3496 mkosi-sandbox: Implement --pack-fds
  mkosi/qemu.py
  mkosi/resources/man/mkosi-sandbox.1.md
  mkosi/run.py
  mkosi/sandbox.py
  tests/__init__.py
Labels: good-to-merge/waiting-for-ci

#3498 kmod: run proper cmdline in modinfo
  mkosi/kmod.py
Labels: good-to-merge/waiting-for-ci

#3506 Fix documented configuration names for --vsock and --vsock-cid
  mkosi/resources/man/mkosi.1.md
Labels: good-to-merge/waiting-for-ci

#3521 ukify: check for 257.999 instead of 258~devel
  mkosi/__init__.py
Labels: good-to-merge/waiting-for-ci

#3525 Search for underscores in `systemd-stub`
  mkosi/__init__.py
Labels: good-to-merge/waiting-for-ci

#3526 Add intel VMD to kernel modules
  mkosi/resources/mkosi-initrd/mkosi.conf
Labels: good-to-merge/waiting-for-ci

#3538 Add --debug-sandbox option to mkosi-initrd and mkosi-addon
  mkosi/addon.py
  mkosi/initrd.py
  mkosi/resources/man/mkosi-addon.1.md
  mkosi/resources/man/mkosi-initrd.1.md
Labels: good-to-merge/waiting-for-ci

#3541 mkosi-obs: use new sd-keyutil verb to attach dm-verity signature
  mkosi/resources/mkosi-obs/mkosi.build
  mkosi/resources/mkosi-obs/mkosi.conf
  mkosi/resources/mkosi-obs/mkosi.postoutput
Labels: good-to-merge/with-minor-suggestions

#3558 Add InitrdProfiles= with initial storage profile
  REUSE.toml
  mkosi/__init__.py
  mkosi/config.py
  mkosi/initrd.py
  mkosi/resources/man/mkosi.1.md
  mkosi/resources/mkosi-initrd/mkosi.conf
  mkosi/resources/mkosi-initrd/mkosi.profiles/storage/mkosi.conf
  mkosi/resources/mkosi-initrd/mkosi.profiles/storage/mkosi.extra/usr/lib/udev/rules.d/10-mkosi-initrd-dm.rules
  mkosi/resources/mkosi-initrd/mkosi.profiles/storage/mkosi.extra/usr/lib/udev/rules.d/10-mkosi-initrd-md.rules
  tests/test_json.py
Labels: ci-fails/needs-rework
