Repository systemd/mkosi, pull requests merged in 2025-03, with the labels that each got.

#3578 Add "raid" initrd profile
  mkosi/config.py
  mkosi/initrd.py
  mkosi/resources/man/mkosi-initrd.1.md
  mkosi/resources/man/mkosi.1.md
  mkosi/resources/mkosi-initrd/mkosi.profiles/raid/mkosi.conf
Labels: good-to-merge/waiting-for-ci

#3584 Revert 9f4d174daac954aaa9e18ee9bb58c6d7a946ec9d
  mkosi/distributions/debian.py
  mkosi/installer/apt.py
Labels: good-to-merge/waiting-for-ci

#3583 Use target path as mount tags
  mkosi/qemu.py
Labels: reviewed/needs-rework

#3585 Rework --run-build-scripts
  mkosi/__init__.py
  mkosi/config.py
  mkosi/resources/man/mkosi.1.md
  tests/test_json.py
Labels: good-to-merge/waiting-for-ci

#3593 Make user provided command line take preference over roothash=
  mkosi/__init__.py
Labels: good-to-merge/waiting-for-ci

#3597 Various fixes
  mkosi/__init__.py
  mkosi/config.py
  mkosi/distributions/arch.py
  mkosi/distributions/centos.py
  mkosi/distributions/debian.py
  mkosi/distributions/fedora.py
  mkosi/distributions/opensuse.py
  mkosi/qemu.py
Labels: good-to-merge/waiting-for-ci

#3599 initrd: Install gzip in all initrds, not just the Arch one
  mkosi/resources/mkosi-initrd/mkosi.conf
  mkosi/resources/mkosi-initrd/mkosi.conf.d/10-arch.conf
Labels: good-to-merge/waiting-for-ci

#3618 Add mkosi init to install a tmpfiles dropin for the cache dir
  mkosi/__init__.py
  mkosi/config.py
  mkosi/resources/man/mkosi.1.md
  mkosi/resources/tmpfiles.d/mkosi.conf
  mkosi/user.py
  pyproject.toml
Labels: good-to-merge/with-minor-suggestions

#3629 config: explicitly type make_simple_config_parser to work with dataclasses
  mkosi/config.py
Labels: good-to-merge/waiting-for-ci

#3634 Pass `DEBUG` enviroment variable to scripts
  mkosi/__init__.py
  mkosi/resources/man/mkosi.1.md
Labels: good-to-merge/waiting-for-ci
